table Fact_Sales
	lineageTag: 78fafdf6-cdcf-4eb0-9b9e-41cd3fdaf9b9

	measure 'Total Sales' =
			
			SUM(Fact_Sales[sales_amount])
		lineageTag: ea75890f-ec20-43ab-839e-e48eafe71648

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			VAR CurrentSales = [Total Sales]
			VAR PreviousSales =
			    CALCULATE(
			        [Total Sales],
			        DATEADD(Dim_Date[date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(CurrentSales - PreviousSales, PreviousSales)
		lineageTag: 28e3b8b4-46dd-4e2e-b4b9-a0ec13ce63e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(Dim_Date[date]),
			        Dim_Date[date] <= MAX(Dim_Date[date])
			    )
			)
		lineageTag: 75639ae6-c8c0-43c9-9273-34e71e2bde6f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'City Sales Rank' =
			
			RANKX(
			    ALL(Dim_City[city]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: cef95275-f677-406b-b650-2603e8ec3fff

	measure 'Cold Brew Sales' =
			
			CALCULATE(
			    [Total Sales],
			    Dim_Product[item] = "Cold Brew"
			)
		lineageTag: ca5f7e22-a601-4de5-ba33-10ae1e12ddbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: 288bca78-6e5e-4f1b-830e-f0c7e5c86c6a
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 36ed1d36-13a9-4264-9f69-1a58a20c526a
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 3995c521-7db2-4e42-8863-e50f59b65b11
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 7c520859-0892-4a90-a150-e31fc729aae0
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 806c7a86-6c22-4925-8352-e1d8589a9ab9
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: c1afd25f-d7ca-47d8-8de2-b49d56591979
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 511d57e7-6c3a-450e-9b99-632f0925ded5
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 17959bc3-5753-421b-bf85-607738ef8e6e
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 686bf16a-a188-4de2-b5e4-499e166201d0
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\DELL\Documents\GitHub\brewmetrics-bi\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

